### ISSUE TITLE
Missing ToadEntity method. 

### ISSUE THREAD

**Issue by Ryan324123123** [rikka0w0/MobZReborn#16]
The game runs until it tries to load this entity I think. Then the game freezes. 
I looked in the config and there is a spawn rate for this entity but no spawn toggle?
Error report: 

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 18/04/22, 11:45 am
Description: Ticking entity

java.lang.NoClassDefFoundError: net/minecraft/class_3494$class_5123
	at net.mobz.entity.ToadEntity.method_5959(ToadEntity.java:100)
	at net.minecraft.class_1308.<init>(class_1308.java:144)
	at net.minecraft.class_1314.<init>(class_1314.java:14)
	at net.minecraft.class_1296.<init>(class_1296.java:28)
	at net.minecraft.class_1429.<init>(class_1429.java:43)
	at net.mobz.entity.ToadEntity.<init>(ToadEntity.java:84)
	at net.minecraft.class_1299.method_5883(class_1299.java:478)
	at net.minecraft.class_1948.method_8661(class_1948.java:519)
	at net.minecraft.class_3754.method_12107(class_3754.java:493)
	at net.minecraft.class_2806.method_17033(class_2806.java:171)
	at net.minecraft.class_2806$class_3768.doWork(class_2806.java:338)
	at net.minecraft.class_2806.method_12154(class_2806.java:289)
	at net.minecraft.class_3898.method_17225(class_3898.java:649)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:643)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_3900.method_17634(class_3900.java:62)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_3494$class_5123
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 27 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.mobz.entity.ToadEntity.method_5959(ToadEntity.java:100)
	at net.minecraft.class_1308.<init>(class_1308.java:144)
	at net.minecraft.class_1314.<init>(class_1314.java:14)
	at net.minecraft.class_1296.<init>(class_1296.java:28)
	at net.minecraft.class_1429.<init>(class_1429.java:43)
	at net.mobz.entity.ToadEntity.<init>(ToadEntity.java:84)
	at net.minecraft.class_1299.method_5883(class_1299.java:478)
	at net.minecraft.class_1948.method_8661(class_1948.java:519)
	at net.minecraft.class_3754.method_12107(class_3754.java:493)
	at net.minecraft.class_2806.method_17033(class_2806.java:171)
	at net.minecraft.class_2806$class_3768.doWork(class_2806.java:338)
	at net.minecraft.class_2806.method_12154(class_2806.java:289)
	at net.minecraft.class_3898.method_17225(class_3898.java:649)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:643)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)

-- Entity being ticked --
Details:
	Entity Type: minecraft:zombie (net.minecraft.class_1642)
	Entity ID: 13512
	Entity Name: Zombie
	Entity's Exact location: 2446.50, 48.00, 1810.50
	Entity's Block location: World: (2446,48,1810), Section: (at 14,0,2 in 152,3,113; chunk contains blocks 2432,-64,1808 to 2447,319,1823), Region: (4,3; contains chunks 128,96 to 159,127, blocks 2048,-64,1536 to 2559,319,2047)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:488)
	at net.minecraft.class_3218.method_31420(class_3218.java:363)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:331)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['hulk765'/484, l='ServerLevel[New World]', x=2438.35, y=70.39, z=1819.48]]
	Chunk stats: 3199
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,104,0), Section: (at 0,8,0 in 0,6,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 13744 game time, 13744 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 146539 (now: false), thunder time: 161393 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil

**Comment by Mykosayyad** [comment]
I got the same issue where my game crashed while trying to load the toad mob
